server:
  port: 8080
  address: 0.0.0.0

spring:
#    password: kzlapgltzlkceade   # 授权码，非登录密码
  application:
    name: intellectual-property

  datasource:
    url: "jdbc:mysql://47.109.39.226:3306/intellectual-property?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&charset=utf8mb4"
    username: root
    password: 060803
    driver-class-name: com.mysql.cj.jdbc.Driver
  api-docs:
    enabled: true
    path: /v3/api-docs
    swagger-ui:
      enabled: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

app:
  upload:
    dir: uploads

logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.datasource: DEBUG
